version: '3.4'

services:
  catalogdb:
    image: mongo
  catalog_api:
    image: ${DOCKER_REGISTRY-}catalog_api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog_API/Dockerfile
volumes:
  mongo_data:
