version: '3.4'

services: 
  
  catalog_api:
    image: ramane/catalog_api
  catalogdb:
    image: mongo
  
  basket_api:
    image: ramane/basket_api
  basketdb:
    image: redis:alpine

  discount_api:
    image: ramane/discount_api
  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce


volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:  
