version: '3.4'

services: 
  
  catalog_api:
    image: ramane/catalog_api
  catalogdb:
    image: mongo
  
  basket_api:
    image: ramane/basket_api
  basketdb:
    image: redis:alpine

  discount_api:
    image: ramane/discount_api
  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce


  dicount_grpc:
    image: ramane/discount_grpc   

  ordering_api:
    image: ramane/ordering_api

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:  


